### ISSUE TITLE
Export and execute the code

### ISSUE THREAD

**Issue by hbcarlos** [QuantStack/jupyterlab-blockly#2]
To execute the code generated by blockly, we can use kernels. The idea would be to add a button in the toolbar to allow the user to run the code and show the output on another widget.

Some documentation to get started:
* [JupyterLab](https://jupyterlab.github.io/jupyterlab/modules/_services_src_index_._services_src_kernel_kernel_.html)
* [Jupyter Client](https://jupyter-client.readthedocs.io/en/stable)
* [Blockly](https://developers.google.com/blockly/guides/configure/web/code-generators)
* [Example kernel messaging](https://github.com/jupyterlab/extension-examples/tree/master/kernel-messaging)
* [Example kernel output](https://github.com/jupyterlab/extension-examples/tree/master/kernel-output)

We can link the document to a kernel, add a small icon in the toolbar to see the status of the kernel, and select a kernel. Once we have a kernel connection, each time the user modifies the code, we can export it and send a completeness message to the kernel to check whether the code could be executed and add a small indicator for the user.
When the user presses the execution button, we can export the code as Python, send it to the kernel with an execution request and show the response in an `OutputAreaWidget`.

- **Completeness message:**
https://jupyter-client.readthedocs.io/en/stable/messaging.html#code-completeness
- **Execute message:**
https://jupyter-client.readthedocs.io/en/stable/messaging.html#execute
- **A simple way of creating a `OutputAreaWidget`:**
https://github.com/voila-dashboards/voila-gridstack/blob/b44f697fab531521503dc23d2da180069987e6f3/packages/jupyterlab-gridstack/src/editor/gridstack/model.ts#L334-L346

**Comment by hbcarlos** [comment]
By default, blockly includes some blocks that we can use to create our toolbox. This set of blocks comes with their corresponding generator to translate the user workspace into code for the following languages:
* JavaScript
* Python
* PHP
* Lua
* Dart

For now, we can start adding support for Python since JupyterLab ships with the IPyKernel as a dependency. To import and use the Python generator in this extension, we must explicitly import it from the blockly package.
```=typescript
import BlocklyPy from 'blockly/python';
```
 Then we can serialize our workspace into Python code as follows:
```=typescript
const code = BlocklyPy.workspaceToCode(this._workspace);
```

The `workspaceToCode` function returns a string ready to send with an execution request to the corresponding kernel. To make an execution request to a kernel and display the outputs, we need a kernel session to send the execution request to a running kernel, an `OutputArea` widget to render the execution response, and the code to execute.

Every document has a context instance that we can use to manage kernels from the document. Since we will want to execute code, we can tell the `BlocklyEditorFactory` to start a kernel for us every time the user opens a document with the Blockly Editor. This way, every instance of the Blockly Editor will have a kernel assigned ready to send execution requests.

```=typescript
const widgetFactory = new BlocklyEditorFactory({
  name: FACTORY,
  modelName: 'text',
  fileTypes: ['json'],
  defaultFor: ['json'],

  // Kernel options, in this case we need to execute the code generated
  // in the blockly editor. The best way would be to use kernels, for
  // that reason, we tell the widget factory to start a kernel session
  // when opening the editor, and close the session when closing the editor.
  canStartKernel: true,
  preferKernel: true,
  shutdownOnClose: true,

  // The rendermime instance, necessary to render the outputs
  // after a code execution.
  rendermime: rendermime
});
```

To render the responses from the kernel, we can use the widget `SimplifiedOutputArea`. This widget requires an instance of the `IRenderMimeRegistry`. We can require the `IRenderMimeRegistry` plugin that JupyterLab provides for that purpose. This plugin already contains all the renders that we need to use to show the execution output to the user.

```=typescript
const plugin: JupyterFrontEndPlugin<IBlocklyManager> = {
  id: 'jupyterlab-blocky:plugin',
  autoStart: true,
  requires: [ILayoutRestorer, IRenderMimeRegistry],
  provides: IBlocklyManager,
  activate: (
    app: JupyterFrontEnd,
    restorer: ILayoutRestorer,
    rendermime: IRenderMimeRegistry
  ): IBlocklyManager => {}
};
```

We can import the `SimplifiedOutputArea` and the `IRenderMimeRegistry` from its corresponding packages as follows:
```=typescript
import { SimplifiedOutputArea, OutputAreaModel } from '@jupyterlab/outputarea';
import { IRenderMimeRegistry } from '@jupyterlab/rendermime';
```

Once we have the rendermime, we can create a `SimplifiedOutputArea` widget to render the outputs from the execution reply.

```=typescript
this._outputArea = new SimplifiedOutputArea({
  model: new OutputAreaModel({ trusted: true }),
  rendermime
});
```

And use the static method from the same class to make an execution request:
```=typescript
const code = this._manager.generator.workspaceToCode(this._workspace);
SimplifiedOutputArea.execute(code, this._outputArea, this._sessionContext)
  .then(resp => {
    this.addWidget(this._outputArea);
    this._resizeWorkspace();
  })
  .catch(e => console.error(e));
```

**Comment by hbcarlos** [comment]
For executing code, would be great to have a button in the toolbar. Here there is an example of adding a button to the notebook toolbar, is probably outdated and the logic in the notebook is a bit different but is a good starting point to understand how to add elements to the toolbar.

https://github.com/jupyterlab/extension-examples/tree/master/toolbar-button

Another way of adding buttons to the toolbar is using commands, here there is a tutorial about commands that is also recommended to look at:

https://github.com/jupyterlab/extension-examples/blob/master/commands/README.md

**Comment by DenisaCG** [comment]
Thank you for the thorough documentation @hbcarlos! Everything worked perfectly!

To add on to it, after using [this way](https://github.com/jupyterlab/extension-examples/tree/master/toolbar-button) to add the button to the toolbar, we also added the jupyterlab run icon to it.

`const button = new ToolbarButton({
      label: 'Run Code',
      icon: runIcon,
      className: 'jp-blockly-button',
      onClick: runCode,
      tooltip: 'Run Code'
    });
    button.addClass('jp-blockly-runButton');
    this.toolbar.addItem('run', button);`

Also, to fix the hover issues we had for the button, cause by the ToolbarButton class, we added the following classes to the base.css file: 

`.jp-blockly-button:hover {
	background-color: transparent !important;
}

.jp-blockly-runButton {
	background-color: var(--md-green-500)
}

.jp-blockly-runButton:hover {
	background-color: var(--md-green-700)
}`

**Comment by DenisaCG** [comment]
Thank you for the thorough documentation @hbcarlos! Everything worked perfectly!

To add on to it, after using [this way](https://github.com/jupyterlab/extension-examples/tree/master/toolbar-button) to add the button to the toolbar, we also added the jupyterlab run icon to it, as it follows:

```
const button = new ToolbarButton({
      label: 'Run Code',
      icon: runIcon,
      className: 'jp-blockly-button',
      onClick: runCode,
      tooltip: 'Run Code'
    });
    button.addClass('jp-blockly-runButton');
    this.toolbar.addItem('run', button);
```

Also, to fix the hover issues we had for the button, cause by the ToolbarButton class, we added the following classes to the base.css file:

```
.jp-blockly-button:hover {
background-color: transparent !important;
}

.jp-blockly-runButton {
background-color: var(--md-green-500)
}

.jp-blockly-runButton:hover {
background-color: var(--md-green-700)
}
```
