### ISSUE TITLE
Set up JupyterLite to demo the extension 

### ISSUE THREAD

**Issue by jtpio** [QuantStack/jupyterlab-blockly#32]
It would be nice to set up a JupyterLite deployment to easily try the extension in the browser.

For example using https://github.com/jupyterlite/jupyterlite-sphinx like in the `ipycanvas` docs: https://ipycanvas.readthedocs.io/en/latest/?badge=latest

**Comment by jtpio** [comment]
Maybe it would be nice to package the extension for conda as well, so we could use the `jupyterlite-xeus-python` kernel.

**Comment by jtpio** [comment]
@hbcarlos @wolfv do you already have ReadTheDocs set up for this project?

Otherwise do you want to add it, and then enable the "Build pull requests for this project"?

![image](https://user-images.githubusercontent.com/591645/177778526-1ebdd3c9-ce1a-4ad1-a20e-bbd652a64154.png)

So we can start using `jupyterlite-sphinx`.

**Comment by hbcarlos** [comment]
Thanks, @jtpio. We are setting it up here #35

**Comment by DenisaCG** [comment]
The documentation is set up here: https://jupyterlab-blockly.readthedocs.io/en/latest/
The conda packaging for the extension allows it to be installed using `conda install -c conda-forge jupyterlab-blockly`
And JupyterLite was set up - embedded in the index page of the `readmedocs` or easily accessible from https://jupyterlab-blockly.readthedocs.io/en/latest/lite/lab/index.html?path=example.jpblockly
