### ISSUE TITLE
Initialize blockly with default blocks

### ISSUE THREAD

**Issue by hbcarlos** [QuantStack/jupyterlab-blockly#4]
Create the default set of blocks for Python. Investigate if Blockly provides a default toolbox for the supported generators or look into other projects using blockly, to extract a basic set of blocks that we can reuse for Python. If we don't find anything, we can always export the default toolbox from the blockly developer tools web page.

Some documentation to get started:
* [Blockly](https://developers.google.com/blockly/guides/configure/web/toolbox)
* [Blockly Developer Tools](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html)

**Comment by DenisaCG** [comment]
Added a toolbox of default set of blocks, based on this [code](https://github.com/google/blockly/issues/4464#issuecomment-812736813).

**Comment by hbcarlos** [comment]
Adding here the link to the ts generators since it could be useful.
https://github.com/daniel-brenot/blockly

**Comment by DenisaCG** [comment]
Some other links that might be useful:

- original repository containing the python generator for the complete toolbox, implemented in Javascript : https://github.com/google/blockly/tree/master/generators

- https://github.com/google/blockly/issues/5857

- https://github.com/google/blockly/issues/2995
