### ISSUE TITLE
Cannot switch kernel (at least in the case of JupyterLite)

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/jupyterlab-blockly#55]
It seems to be stuck with the kernel selected upon opening the document.

**Comment by hbcarlos** [comment]
This seams to be a issue with JupyterLite

https://user-images.githubusercontent.com/26092748/181743523-63a12862-7217-4e45-9055-ac0d236e890b.mp4

**Comment by hbcarlos** [comment]
I've moved the issue to lite.

**Comment by SylvainCorlay** [comment]
Thanks, excellent catch.
