### ISSUE TITLE
Error when importing the `IBlocklyRegistry` token

### ISSUE THREAD

**Issue by DenisaCG** [QuantStack/jupyterlab-blockly#64]
When importing the `IBlocklyRegistry` token in another extension, I'm getting the following error:
```
Plugin 'jupyterlab-lego-boost:plugin' failed to activate.
Error: No provider for: jupyterlab-blockly/registry.
    at e.resolveRequiredService (jlab_core.ace489612104403d9b5e.js?v=ace489612104403d9b5e:2:1343887)
    at jlab_core.ace489612104403d9b5e.js?v=ace489612104403d9b5e:2:1343444
    at Array.map (<anonymous>)
    at e.activatePlugin (jlab_core.ace489612104403d9b5e.js?v=ace489612104403d9b5e:2:1343418)
    at jlab_core.ace489612104403d9b5e.js?v=ace489612104403d9b5e:2:1344610
    at Array.map (<anonymous>)
    at e.start (jlab_core.ace489612104403d9b5e.js?v=ace489612104403d9b5e:2:1344584)
    at G (7796.25a9965c8e0e6c74a3ed.js?v=25a9965c8e0e6c74a3ed:1:8374)
```

The code used to import the `IBlocklyRegistry` token in the extension is (code snippet taken from this [PR](https://github.com/QuantStack/jupyterlab-lego-boost/pull/1)): 
```typescript
import { IBlocklyRegistry } from 'jupyterlab-blockly';

/**
 * Initialization data for the jupyterlab-lego-boost extension.
 */
const plugin: JupyterFrontEndPlugin<void> = {
  id: 'jupyterlab-lego-boost:plugin',
  autoStart: true,
  requires: [IBlocklyRegistry],
  activate: (app: JupyterFrontEnd, blockly: IBlocklyRegistry) => {
    console.log('JupyterLab extension jupyterlab-lego-boost is activated!');
  }
};
```

I started getting this error after we made the latest patch release `0.1.1`, in order to incorporate this PR https://github.com/QuantStack/jupyterlab-blockly/pull/62 which fixes a typo regarding the spelling of the `IBlocklyRegistry`. As far as I investigated, nothing else was changed regarding the logic of the code. The `JupyterLab-Niryo-One` extension is using the `0.1.0` version and everything works perfectly, the code base can be seen [here](https://github.com/QuantStack/jupyterlab-niryo-one).

From the documentation I read it might be a problem from the  deduplication of dependencies, but we didn't change anything there in the new release. The `package.json` file:

https://github.com/QuantStack/jupyterlab-blockly/blob/6667d0e2b7fc69b688bdc2fff3542dc5d05ae3cc/packages/blockly-extension/package.json#L71-L84

I also noticed that when installing the extension locally in my environment, using `pip install jupyterlab-blockly`, the error is fixed. 

NOTE: The `IBlocklyRegistry` is the class that the `JupyterLab-Blockly` extension exposes to other plugins. This registry allows other plugins to register new Toolboxes, Blocks and Generators that users can use in the Blockly editor. So, it is essential when creating an extension on top of `JupyterLab-Blockly`.

**Comment by fcollonval** [comment]
@DenisaCG you should indeed request the `jupyterlab-blockly` package to be a dependency of `jupyterlab-lego-boost` to ensure it is installed and available to provide the token.

See [JupyterLab-Niryo-One config](https://github.com/QuantStack/jupyterlab-niryo-one/blob/d19b1ce213fae665dc518fd7ebf0a2c30771af74/setup.py#L57)

**Comment by fcollonval** [comment]
Small note, you should also add to `jupyterlab-lego-boost` package.json the following configuration:

```json
"jupyterlab": {
  "sharedPackages": {
     "jupyterlab-blockly": { 
       "bundled": false, 
       "singleton": true 
     }, 
     "blockly": { 
       "bundled": false, 
       "singleton": true 
     } 
   }
 }
```

**Comment by DenisaCG** [comment]
Thank you for the help @fcollonval! 

After modifying the `setup.py` with the configuration, I'm still getting the same error. Also after configuring the `package.json` I get the following error: 

```
Error: Shared module jupyterlab-blockly doesn't exist in shared scope default
    at ensureExistence (consumes:19:1)
    at consumes:101:1
    at consumes:82:1
    at webpack/sharing/consume/default/jupyterlab-blockly (consumes:134:1)
    at consumes:161:1
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (consumes:144:1)
    at ensure chunk:6:1
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (ensure chunk:5:1)
```

**Comment by DenisaCG** [comment]
The changes suggested worked, but we realized that package `jupyterlab-blockly` was not yet installed in the enviroment. This was fixed by just running the following commands:
```
pip install -e .[test]
jupyter labextension develop --overwrite .
```

Thank you @fcollonval for all the help in debugging this!
