### ISSUE TITLE
jupyterlab blockly language is not English blocks

### ISSUE THREAD

**Issue by runtimevic** [QuantStack/jupyterlab-blockly#82]
Hi , 
jupyterlab blockly language is not English blocks...
How can i fix it?
thanks you

**Comment by DenisaCG** [comment]
Hey @runtimevic.

The toolbox should automatically adapt to the language you are using in JupyterLab. Once you switch the language in JupyterLab to English, it should also switch the language for the blocks inside the toolbox to English.

The development install also includes two other language packages (Spanish and French), only for testing purposes of the internationalization. Maybe JupyterLab is automatically switching to one of those languages, but going back to English should still be possible.

Currently, there seems to be an issue which makes `jupyterlab-blockly` activate in Lithuanian. I will investigate it further. For now, you can try switching to another language in JupyterLab, such as Spanish, and then back to English and your toolbox should appear in the chosen language. 

Thank you for opening this issue!

**Comment by DenisaCG** [comment]
This issue is the same as: https://github.com/QuantStack/jupyterlab-blockly/issues/81. Further discussions and solutions can be continued there.
